# For Atom build
atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _posts

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               艾倫．可行．行動．能行(Allen．Feasible．Action．Success)<br>
tagline:             'Allen FAS'
description:         'A reserved <a href="https://hcchen.github.io/Allen_FAS/" target="_blank">Allen FAS</a>  Blog  made by <a href="https://twitter.com/hcchen1113" target="_blank">@allen</a>.'
url:                 https://hcchen.github.io/Allen_FAS/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allen Chen
  url:               https://twitter.com/hcchen1113
  email:             hsiehchang.chen@gmail.com

# Custom vars
version:             1.0.0
# Custom url
hr_url:            https://www.hackerrank.com
kaggle_url:        https://www.kaggle.com
leecode_url:       https://leetcode.com
# Jekyll plugins
gems:
  - jekyll-sitemap
