# Permalinks
# https://jekyllrb.com/docs/permalinks/ Don't set permalink for paginate work
#permalink:           pretty

title:               艾倫．可行．行動．能行(Allen．Feasible．Action．Success)
tagline:             'Allen FAS'
description:         'A reserved <a href="https://hcchen.github.io/Allen_FAS/" target="_blank">Allen FAS</a>  Blog  made by <a href="https://twitter.com/hcchen1113" target="_blank">@allen</a>.'
url:                 https://hcchen.github.io/Allen_FAS
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allen Chen
  url:               https://twitter.com/hcchen1113
  email:             hsiehchang.chen@gmail.com

# Custom vars
version:             1.0

# Custom url
hr_url:              https://www.hackerrank.com
kaggle_url:          https://www.kaggle.com
leecode_url:         https://leetcode.com
farmbot_url:         https://farmbot.io/

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Jekyll theme
#theme: jekyll-theme-cayman
theme: jekyll-theme-minimal

## https://medium.com/@vilcins/syntax-highlight-with-rouge-in-jekyll-6bf9e45f9dda
highlighter:         rouge

#Set the time zone for site generation
timezone:            Asia/Taipei
#Enable the experimental incremental build feature. Incremental build only re-builds posts and pages that have changed, resulting in significant performance improvements for large sites, but may also break site generation in certain cases.
incremental:          false
