# Permalinks
# https://jekyllrb.com/docs/permalinks/
# pretty : /:categories/:year/:month/:day/:title/
permalink:           pretty
# Use of `relative_permalinks` ensures post links from the index work properly.
#relative_permalinks: true

# Setup
title:               艾倫．可行．行動．能行(Allen．Feasible．Action．Success)
tagline:             'Allen FAS'
description:         'A reserved <a href="https://hcchen.github.io/Allen_FAS/" target="_blank">Allen FAS</a>  Blog  made by <a href="https://twitter.com/hcchen1113" target="_blank">@allen</a>.'
url:                 https://hcchen.github.io/Allen_FAS
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allen Chen
  url:               https://twitter.com/hcchen1113
  email:             hsiehchang.chen@gmail.com

# Custom vars
version:             1.0

# Custom url
hr_url:            https://www.hackerrank.com
kaggle_url:        https://www.kaggle.com
leecode_url:       https://leetcode.com
farmbot_url:       https://farmbot.io/

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Collections Dir
collections_dir: data
collections:
    cs:
      output: true

#theme: jekyll-theme-cayman
theme: jekyll-theme-minimal


## https://medium.com/@vilcins/syntax-highlight-with-rouge-in-jekyll-6bf9e45f9dda
highlighter: rouge
